# Generated by Django 5.2.17 on 2026-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(default=1, editable=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("entry_date", models.DateField()),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rough", "Rough"),
                            ("okay", "Okay"),
                            ("good", "Good"),
                            ("great", "Great"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-entry_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-entry_date"], name="entry_user_date_idx"
                    ),
                    models.Index(
                        fields=["user_id", "-updated_at"], name="entry_user_updated_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "entry_date"), name="unique_user_entry_date"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("mood__isnull", True),
                            ("mood__in", ["rough", "okay", "good", "great"]),
                            _connector="OR",
                        ),
                        name="valid_entry_mood",
                    ),
                ],
            },
        ),
    ]
